# WCRP Coupled Model Intercomparison Project (CMIP)

CMIP -> Calcular la sensibilidad de clima mediante un ensamble de modelos

The uncertainty associated with the speed of temperature rise is associated with the limitations of our understanding of the global climate system. Each general circulation model used by the IPCC and included in the CMIP5 ensemble uses different assumptions and parameter values to describe the atmospheric changes resulting in growing anthropogenic GHG emissions, and, as a result, the magnitude of the estimated changes varies greatly among different modeling groups. In this respect, one of the features of EDIAM is that it uses 12 GCMs included in the CMIP5 data ensemble to calibrate the parameters


* $\beta$ :  sensibilidad de la atmósfera a emisiones de $CO_2$ (grados celsius)
* $\xi$ : la capacidad de sumidero de carbono de la atmósfera (ppm/BTU/year)
* $\delta$: tasa promedio de regeneración ambiental natural

In [79]:
## Cargamos bibliotecas
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import math
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import scipy.stats
import math
import os

In [80]:
#PART1: CALIBRATION OF DELTA TEMP VS LOG CO2 FUNCTION
# Cargamos los datos del csv AllGCMs.csv, los cuales contienen
climate_models = pd.read_csv("/home/milo/PCIC/Maestría/2doSemestre/seminario/github/data/cmip5/gcm_year.csv")

climate_models = climate_models.query("year < 2096")
# [degrees Celsius] increase in average global temperature
delta_temp_disater = 7.5  

cmip_models = ["MRI-ESM1","GFDL-ESM2G"]

def linear_reg(datos,modelo,region,intercepto):
    print("Climate model:{}\nRegion:{}".format(modelo,region))
    model_data = datos[datos["climate_model"]==modelo]
    if modelo == "MRI-ESM1":
        model_data = model_data.query("year <2091")
    model_data = model_data.query("region=='{}'".format(region)) 
    n = model_data.query("variable == 'co2'").shape[0]

    X = model_data.query("variable == 'co2'")["value"].apply(math.log).values.reshape(n,1)
    Y = model_data.query("variable == 'tas'")["value"].values.reshape(n,1)

    if intercepto:
        regress = LinearRegression().fit(X,Y)
        R2 = regress.score(X,Y)
        Y_pred= regress.predict(X)
        MSE = mean_squared_error(Y_pred,Y)
        b0 = regress.intercept_[0]
        b1 = regress.coef_[0][0]

        var_b0= (1/n) * ((MSE*np.square(X).sum())/np.square(X -X.mean()).sum())
        var_b1 = MSE/np.square(X -X.mean()).sum()
        t_b0 = b0/math.sqrt(var_b0)
        t_b1 = b1/math.sqrt(var_b1)

        pvalue_b0 = scipy.stats.t.sf(abs(t_b0),n-2)
        pvalue_b1 = scipy.stats.t.sf(abs(t_b1),n-2)

        d = {"climate_model": [modelo],
             "region" : [region],
             "beta_delta_temp":[b1],
             "intercept":[b0],
             "adjR_squared": [R2],
             "intercept_P_value": [pvalue_b0],
             "beta_P_value":  [pvalue_b0]}
        df = pd.DataFrame(data=d)
    else:
        regress = LinearRegression(fit_intercept=False).fit(X,Y)
        df = regress.coef_[0][0]
        

    return df

# Para cada modelo realizamos una regresión lineal entre log(co2.ppm) y tas.anomaly
result = pd.DataFrame()

for model in cmip_models:
    for region in climate_models["region"].unique():
        result = result.append(linear_reg(climate_models,model,region,True), ignore_index=True)

#estimate CO2 concentrations for delta temp disaster

result['co2_base'] = (-1*result['intercept']/result['beta_delta_temp']).apply(math.exp)
result['co2_disaster'] =result['co2_base']*(delta_temp_disater/result['beta_delta_temp']).apply(math.exp)
result['delta_temp_disaster'] = delta_temp_disater
result

Climate model:MRI-ESM1
Region:america
Climate model:MRI-ESM1
Region:eurafrica
Climate model:MRI-ESM1
Region:asia
Climate model:GFDL-ESM2G
Region:america
Climate model:GFDL-ESM2G
Region:eurafrica
Climate model:GFDL-ESM2G
Region:asia

,climate_model,region,beta_delta_temp,intercept,adjR_squared,intercept_P_value,beta_P_value,co2_base,co2_disaster,delta_temp_disaster
0,MRI-ESM1,america,4.178186,-82.494817,0.972215,6.639099e-188,6.639099e-188,3.756516e+08,2.261311e+09,7.5
1,MRI-ESM1,eurafrica,4.610689,-91.034290,0.967210,2.431481e-179,2.431481e-179,3.756564e+08,1.910900e+09,7.5
2,MRI-ESM1,asia,4.138133,-81.704314,0.968660,1.115444e-181,1.115444e-181,3.756783e+08,2.301104e+09,7.5
3,GFDL-ESM2G,america,3.036452,-18.048002,0.906700,4.192734e-244,4.192734e-244,3.813739e+02,4.508720e+03,7.5
4,GFDL-ESM2G,eurafrica,3.321932,-19.743692,0.924347,1.989261e-265,1.989261e-265,3.812432e+02,3.645176e+03,7.5
5,GFDL-ESM2G,asia,3.534413,-21.005082,0.933572,1.280951e-278,1.280951e-278,3.810832e+02,3.181190e+03,7.5

In [81]:
climate_models = climate_models[["year","climate_model","region","variable","value"]].groupby(["year","climate_model","region","variable"], as_index=False).sum()
climate_models = climate_models.pivot(index= ["year","climate_model","region"], columns ="variable",values="value").reset_index()
climate_models

variable  year climate_model     region           co2       co2mass       tas
0         1851      MRI-ESM1    america  2.868757e+08  2.224402e+15 -1.263442
1         1851      MRI-ESM1       asia  2.868631e+08  2.224402e+15 -1.059283
2         1851      MRI-ESM1  eurafrica  2.868743e+08  2.224402e+15 -1.182182
3         1852      MRI-ESM1    america  2.865196e+08  2.222210e+15 -0.759429
4         1852      MRI-ESM1       asia  2.865143e+08  2.222210e+15 -0.981110
...        ...           ...        ...           ...           ...       ...
2140      2095    GFDL-ESM2M       asia  5.342060e+02  1.441319e+16  5.064351
2141      2095    GFDL-ESM2M  eurafrica  5.336970e+02  1.441319e+16  4.283394
2142      2095      MRI-ESM1    america  8.716942e+08  6.895200e+15       NaN
2143      2095      MRI-ESM1       asia  8.718223e+08  6.895200e+15       NaN
2144      2095      MRI-ESM1  eurafrica  8.717695e+08  6.895200e+15       NaN

[2145 rows x 6 columns]

In [82]:
result["id"] =result["climate_model"] + result["region"]
climate_models["id"] =climate_models["climate_model"] + climate_models["region"]

In [83]:
#PART2: CALIBRATION OF S EQUATION
climate_models = climate_models.query("year < 2091")
#merge CO2 Disaster with raw data
climate_models = climate_models.merge(result[['id','co2_disaster']], how='inner', on='id')
climate_models.drop(columns="id",inplace=True)
climate_models

,year,climate_model,region,co2,co2mass,tas,co2_disaster
0,1851,MRI-ESM1,america,2.868757e+08,2.224402e+15,-1.263442,2.261311e+09
1,1852,MRI-ESM1,america,2.865196e+08,2.222210e+15,-0.759429,2.261311e+09
2,1853,MRI-ESM1,america,2.863493e+08,2.223623e+15,-1.039173,2.261311e+09
3,1854,MRI-ESM1,america,2.860947e+08,2.224030e+15,-1.033081,2.261311e+09
4,1855,MRI-ESM1,america,2.859785e+08,2.225144e+15,-0.969982,2.261311e+09
...,...,...,...,...,...,...,...
1405,2086,GFDL-ESM2G,eurafrica,1.326815e+03,1.046046e+16,3.867727,3.645176e+03
1406,2087,GFDL-ESM2G,eurafrica,1.337368e+03,1.053064e+16,3.891684,3.645176e+03
1407,2088,GFDL-ESM2G,eurafrica,1.346296e+03,1.060108e+16,3.606454,3.645176e+03
1408,2089,GFDL-ESM2G,eurafrica,1.354715e+03,1.067207e+16,3.678633,3.645176e+03
1409,2090,GFDL-ESM2G,eurafrica,1.365056e+03,1.074401e+16,4.262671,3.645176e+03

In [84]:
#calculate quality of the environment
climate_models['s'] = climate_models['co2_disaster'] - climate_models['co2']

#order data set
climate_models = climate_models.sort_values(by = ['climate_model','year'])
climate_models

,year,climate_model,region,co2,co2mass,tas,co2_disaster,s
720,1861,GFDL-ESM2G,america,5.715042e+02,4.461347e+15,-1.515141,4.508720e+03,3.937216e+03
950,1861,GFDL-ESM2G,asia,5.716090e+02,4.461347e+15,-1.395131,3.181190e+03,2.609581e+03
1180,1861,GFDL-ESM2G,eurafrica,5.713125e+02,4.461347e+15,-1.117568,3.645176e+03,3.073864e+03
721,1862,GFDL-ESM2G,america,5.723358e+02,4.463318e+15,-1.485765,4.508720e+03,3.936384e+03
951,1862,GFDL-ESM2G,asia,5.724693e+02,4.463318e+15,-1.771122,3.181190e+03,2.608720e+03
...,...,...,...,...,...,...,...,...
478,2089,MRI-ESM1,asia,8.183491e+08,6.475905e+15,3.261926,2.301104e+09,1.482755e+09
718,2089,MRI-ESM1,eurafrica,8.182601e+08,6.475905e+15,3.704114,1.910900e+09,1.092640e+09
239,2090,MRI-ESM1,america,8.271332e+08,6.544411e+15,3.563306,2.261311e+09,1.434177e+09
479,2090,MRI-ESM1,asia,8.272585e+08,6.544411e+15,3.453369,2.301104e+09,1.473846e+09
719,2090,MRI-ESM1,eurafrica,8.271338e+08,6.544411e+15,3.686889,1.910900e+09,1.083767e+09

In [104]:
#load data of world consumption of fossil fuels
fossil_fuel = pd.read_csv("/home/milo/PCIC/Maestría/2doSemestre/seminario/github/data/climate_data_calibration/energia_fosil_total_regiones.csv")
fossil_fuel = fossil_fuel.query("energia =='fosil'")
fossil_fuel.loc[fossil_fuel["region"]=="America","region"] = "america"
fossil_fuel.loc[fossil_fuel["region"]=="Asia-Oceania","region"] = "asia"
fossil_fuel.loc[fossil_fuel["region"]=="Eurafrica","region"] = "eurafrica"

fossil_fuel = fossil_fuel[["year","region","value"]].rename(columns = {'value':'fossil_fuels_consumption'})
fossil_fuel

    year     region  fossil_fuels_consumption
0   1980    america                  89.46194
1   1980       asia                  52.11488
2   1980  eurafrica                 113.72357
3   1981    america                  86.67770
4   1981       asia                  52.50440
..   ...        ...                       ...
94  2011       asia                 222.85927
95  2011  eurafrica                 108.06058
96  2012    america                 114.84215
97  2012       asia                 227.25261
98  2012  eurafrica                 108.22853

[99 rows x 3 columns]

In [111]:
def compute_delta(datos,modelo,region):
    datos = datos.query("climate_model == '{}' and region == '{}'".format(modelo,region)).reset_index(drop=True)
    datos["s_diff"]= datos["s"].diff() 
    model_data = datos.merge(fossil_fuel.query("region == '{}'".format(region))[["year","fossil_fuels_consumption"]], how = "right" ,on = "year" )    

        
    n = model_data.shape[0]

    X = model_data['fossil_fuels_consumption'].values.reshape(n,1)
    Y = model_data['s_diff'].values.reshape(n,1)

    regress = LinearRegression(fit_intercept=False).fit(X,Y)
    qsi =   regress.coef_[0][0]/-0.5

    #estimate Delta.S

    model_data['s_lag'] = model_data['s']-model_data['s_diff']
    Y = model_data['s_lag'].values.reshape(n,1)
    regress = LinearRegression(fit_intercept=False).fit(X,Y)
    Delta_S = (0.5*qsi)/regress.coef_[0][0]

    #calculate S_hat
    model_data['s_hat'] = (-1*qsi*model_data['fossil_fuels_consumption'])+((1+Delta_S)*model_data['s_lag'])
    
    d = {"climate_model" :[modelo],
         "region" : [region],
         "qsi":[qsi],
         "delta_s":[Delta_S],
         "s_0":model_data[model_data["year"]==2012]["s_hat"].values}
    df = pd.DataFrame(data=d)
    return df

In [114]:
#we make the same assumption as Acemoglous et. al, such that Delta.S=0.5(qsi*Y(t)/S(t-1));
#thus the original model: S(t)=-qsi*Y(t)+(1+Delta.S)*S(t-1) is reduced to: S(t)-S(t-1)=-0.5*qsi*Y(t)
#and can be estimated with lm

s_parameters = pd.DataFrame()

for model in climate_models["climate_model"].unique():
    for region in ["america","eurafrica","asia"]:
        s_parameters = s_parameters.append(compute_delta(climate_models,model,region), ignore_index=True)

s_parameters

  climate_model     region           qsi   delta_s           s_0
0    GFDL-ESM2G    america      0.065601  0.000904  3.729605e+03
1    GFDL-ESM2G  eurafrica      0.060625  0.001153  2.867159e+03
2    GFDL-ESM2G       asia      0.050550  0.001453  2.397961e+03
3      MRI-ESM1    america  32813.096859  0.000901  1.872524e+09
4      MRI-ESM1  eurafrica  30229.106293  0.001084  1.522578e+09
5      MRI-ESM1       asia  25460.018234  0.000926  1.910355e+09

In [130]:
#Create a table with parameters for all climate models
climate_param_ini = result[["climate_model","beta_delta_temp","co2_base","co2_disaster","delta_temp_disaster","id"]]
s_parameters["id"] = s_parameters["climate_model"] + s_parameters["region"]
s_parameters.drop(columns="climate_model",inplace=True)
climate_param = climate_param_ini.merge(s_parameters,how ="inner", on="id")
climate_param.drop(columns='id',inplace=True)
climate_param.query("climate_model =='GFDL-ESM2G'")

,climate_model,beta_delta_temp,co2_base,co2_disaster,delta_temp_disaster,region,qsi,delta_s,s_0
3,GFDL-ESM2G,3.036452,381.373907,4508.719793,7.5,america,0.065601,0.000904,3729.604678
4,GFDL-ESM2G,3.321932,381.243179,3645.176450,7.5,eurafrica,0.060625,0.001153,2867.159415
5,GFDL-ESM2G,3.534413,381.083179,3181.189645,7.5,asia,0.050550,0.001453,2397.961216

### ENERGIAS POR ECONOMÍAS

In [153]:
fosil_regiones_lideres = pd.read_csv("/home/milo/PCIC/Maestría/2doSemestre/seminario/github/data/climate_data_calibration/energia_fosil_desagregado_lideres_regiones.csv")
renovables_regiones_lideres = pd.read_csv("/home/milo/PCIC/Maestría/2doSemestre/seminario/github/data/climate_data_calibration/energia_renovable_total_lideres_regiones.csv")

list(fosil_regiones_lideres.query("economia=='advanced' and (energia=='carbon' or energia =='petroleo')").sort_values(by="year").value)

[22.15037,
 14.54074,
 40.88987,
 20.55854,
 38.25728,
 1.54837,
 21.61148,
 38.42535,
 21.05922,
 35.55293,
 13.76381,
 1.50822,
 38.10741,
 12.96325,
 33.35381,
 22.33587,
 20.25839,
 1.4411999999999998,
 37.23772,
 23.72908,
 32.9227,
 1.56643,
 12.71399,
 19.12118,
 34.100719999999995,
 1.94094,
 36.70681999999999,
 20.44938,
 13.31105,
 26.41226,
 28.46968,
 19.90765,
 36.73697,
 2.06259,
 13.08079,
 33.96105,
 18.75167,
 35.247249999999994,
 37.59639,
 29.81907,
 13.41643,
 2.1213,
 19.78348,
 38.00791,
 36.04638,
 31.14549,
 13.78948,
 2.18446,
 37.55738,
 14.743190000000002,
 2.27334,
 32.65432,
 20.81902,
 37.97109,
 15.3383,
 33.56461,
 37.69222,
 37.69718,
 2.39189,
 22.06255,
 2.7107,
 22.01408,
 15.67067,
 36.98597,
 34.00572,
 36.83358,
 16.22829,
 36.13862,
 36.32576,
 2.88555,
 22.46945,
 42.419920000000005,
 36.90892,
 16.73035,
 27.50533,
 2.89379,
 34.83236,
 23.35345,
 31.45459,
 2.96397,
 37.16007,
 15.69595,
 23.96536,
 27.36988,
 18.06365,
 26.36684,
 24.56148,
 38.025560000000006,
 32.15411,
 3.1203000000000003,
 26.76038,
 3.21987,
 25.60394,
 37.98334,
 32.31034,
 18.52729,
 26.06894,
 19.08961,
 3.41635,
 39.34054,
 26.02283,
 32.07516,
 19.63108,
 25.07888,
 3.54557,
 26.17638,
 39.9865,
 32.29487,
 3.66752,
 25.69488,
 40.65303,
 32.76959,
 25.6464,
 19.56105,
 41.80884,
 32.47883,
 25.93966,
 26.08825,
 3.88253,
 20.37416,
 26.87516,
 3.98316,
 26.71295,
 42.23696,
 32.40162,
 20.98601,
 27.13376,
 32.83831,
 4.08011,
 42.18724,
 21.00243,
 25.96265,
 27.9,
 4.38244,
 21.29169,
 42.24414,
 32.78203,
 26.7533,
 43.05425,
 33.05093,
 4.46828,
 29.06315,
 22.39598,
 26.2879,
 33.37125,
 44.6888,
 30.13377,
 4.70723,
 26.34756,
 23.89864,
 24.66869,
 25.79435,
 44.83748,
 30.47677,
 5.01983,
 33.567499999999995,
 25.31596,
 33.4484,
 5.71734,
 44.37832,
 25.63018,
 31.39986,
 26.79868,
 33.22245,
 44.35595,
 25.41964,
 6.56968,
 30.90282,
 26.8594,
 33.45404,
 41.72873,
 6.73175,
 31.3938,
 25.45612,
 26.50895,
 7.136,
 28.562,
 39.66991,
 25.28542,
 31.6531,
 8.03122,
 31.76986,
 32.07825,
 27.48505,
 40.48025,
 27.19591,
 9.56228,
 30.659750000000003,
 31.82099,
 28.108400000000003,
 28.38192,
 39.87477,
 30.560630000000003,
 39.17759,
 10.04491,
 29.25615,
 29.91149,
 31.09279]

In [184]:
renovables_regiones_lideres.query("economia=='emerging' and region =='Eurafrica'").sort_values(by="year")

     year     region    energia    value  economia
165  1980  Eurafrica  renovable  2.17530  emerging
166  1981  Eurafrica  renovable  2.24729  emerging
167  1982  Eurafrica  renovable  2.24942  emerging
168  1983  Eurafrica  renovable  2.35983  emerging
169  1984  Eurafrica  renovable  2.23377  emerging
170  1985  Eurafrica  renovable  2.22566  emerging
171  1986  Eurafrica  renovable  2.22165  emerging
172  1987  Eurafrica  renovable  2.33660  emerging
173  1988  Eurafrica  renovable  2.41370  emerging
174  1989  Eurafrica  renovable  2.47249  emerging
175  1990  Eurafrica  renovable  2.51049  emerging
176  1991  Eurafrica  renovable  2.21984  emerging
177  1992  Eurafrica  renovable  2.39133  emerging
178  1993  Eurafrica  renovable  2.45214  emerging
179  1994  Eurafrica  renovable  2.46019  emerging
180  1995  Eurafrica  renovable  2.54388  emerging
181  1996  Eurafrica  renovable  2.34424  emerging
182  1997  Eurafrica  renovable  2.46724  emerging
183  1998  Eurafrica  renovable  2.57834  emerging
184  1999  Eurafrica  renovable  2.84309  emerging
185  2000  Eurafrica  renovable  3.00921  emerging
186  2001  Eurafrica  renovable  2.96736  emerging
187  2002  Eurafrica  renovable  2.97061  emerging
188  2003  Eurafrica  renovable  2.70833  emerging
189  2004  Eurafrica  renovable  2.82675  emerging
190  2005  Eurafrica  renovable  3.12346  emerging
191  2006  Eurafrica  renovable  3.12856  emerging
192  2007  Eurafrica  renovable  3.26986  emerging
193  2008  Eurafrica  renovable  3.43413  emerging
194  2009  Eurafrica  renovable  3.38704  emerging
195  2010  Eurafrica  renovable  3.50218  emerging
196  2011  Eurafrica  renovable  3.45777  emerging
197  2012  Eurafrica  renovable  3.71644  emerging

In [185]:
fosil_regiones_lideres.query("economia=='emerging' and (energia=='carbon' or energia =='petroleo') and region=='Eurafrica'").sort_values(by="year")

     year     region   energia     value  economia
165  1980  Eurafrica    carbon   4.77858  emerging
561  1980  Eurafrica  petroleo  14.45093  emerging
166  1981  Eurafrica    carbon   4.56850  emerging
562  1981  Eurafrica  petroleo  13.31262  emerging
563  1982  Eurafrica  petroleo  13.29260  emerging
..    ...        ...       ...       ...       ...
195  2010  Eurafrica    carbon  10.63961  emerging
592  2011  Eurafrica  petroleo  12.46168  emerging
196  2011  Eurafrica    carbon  10.67637  emerging
197  2012  Eurafrica    carbon  10.61938  emerging
593  2012  Eurafrica  petroleo  12.60532  emerging

[66 rows x 5 columns]

In [186]:
12.60532 + 10.61938

23.2247